services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '80:80'
    volumes:
    - C:\Users\lucas.goulart\Desktop\Workspace\Docker\docker-project-1:/usr/local/apache2/htdocs
